// This file was generated by the OpenAPI Generator
export interface AddBookingModelRequest {
  userId: number;
  gameId: number;
  gameName: string;
  centerId: number;
  location: string;
  slots: number[];
  date: string;
  slotDate: string;
  timeSlot: string;
  player: number;
  price: number;
}