// This file was generated by the OpenAPI Generator
export interface Game {
  id: number;
  name: string;
  description?: string;
  imageUrl?: string;
  videoUrl?: string;
  minPlayers?: number;
  maxPlayers?: number;    
  pricePerHour?: number;
}